import type { Career } from "./index";

export const careers: Career[] = [
  {
    slug: "frontend-developer",
    title: "Frontend Developer",
    description: "Создание пользовательского интерфейса веб-сайтов и приложений",
    level: "beginner",
    skills: ["HTML/CSS", "JavaScript", "React", "Next.js"],
    whatDoes: [
      "Превращает визуальную часть веб-сайтов в код",
      "Делает пользовательский интерфейс (UI) адаптивным",
      "Получает данные из API и отображает на странице",
      "Работает в сотрудничестве с дизайнером",
    ],
    companyRole: "В команде инженеров — мост между дизайном и бэкендом. Отвечает за всё, что видит пользователь.",
    roadmap: [
      { level: "Junior", title: "Junior Frontend", skills: ["HTML/CSS", "Основы JavaScript", "Git"], duration: "0-6 мес", salary: "$300–600" },
      { level: "Middle", title: "Middle Frontend", skills: ["React/Next.js", "TypeScript", "REST API", "Testing"], duration: "6-18 мес", salary: "$600–1,200" },
      { level: "Senior", title: "Senior Frontend", skills: ["Architecture", "Performance", "CI/CD", "Mentoring"], duration: "2-4 года", salary: "$1,200–2,500" },
      { level: "Lead", title: "Tech Lead / Architect", skills: ["System Design", "Team Management", "Strategy"], duration: "4+ лет", salary: "$2,500–4,000" },
    ],
  },
  {
    slug: "backend-developer",
    title: "Backend Developer",
    description: "Серверная часть, API и работа с базами данных",
    level: "middle",
    skills: ["Node.js", "Python", "PostgreSQL", "REST API"],
    whatDoes: [
      "Пишет серверную логику (API, авторизация, бизнес-логика)",
      "Проектирует и управляет базами данных",
      "Занимается безопасностью и оптимизацией производительности",
      "Разрабатывает архитектуру системы",
    ],
    companyRole: "В команде инженеров — невидимая, но важнейшая часть системы. Отвечает за все данные и бизнес-логику.",
    roadmap: [
      { level: "Junior", title: "Junior Backend", skills: ["Node.js/Python", "Основы SQL", "REST API", "Git"], duration: "0-6 мес", salary: "$300–700" },
      { level: "Middle", title: "Middle Backend", skills: ["Database design", "Auth/Security", "Docker", "Testing"], duration: "6-18 мес", salary: "$700–1,500" },
      { level: "Senior", title: "Senior Backend", skills: ["System design", "Microservices", "Performance", "Cloud"], duration: "2-4 года", salary: "$1,500–3,000" },
      { level: "Lead", title: "Tech Lead / Architect", skills: ["Architecture decisions", "Team leading", "DevOps"], duration: "4+ лет", salary: "$3,000–5,000" },
    ],
  },
  {
    slug: "ui-ux-designer",
    title: "UI/UX Designer",
    description: "Проектирование пользовательского опыта и дизайн интерфейса",
    level: "beginner",
    skills: ["Figma", "Prototyping", "User Research", "Design Systems"],
    whatDoes: [
      "Создаёт дизайн пользовательских интерфейсов (UI)",
      "Исследует пользовательский опыт (UX research)",
      "Создаёт вайрфреймы и прототипы",
      "Управляет дизайн-системой и библиотекой компонентов",
    ],
    companyRole: "В продуктовой команде — переводчик между пользователем и технологией. Отвечает за удобство продукта.",
    roadmap: [
      { level: "Junior", title: "Junior Designer", skills: ["Основы Figma", "UI fundamentals", "Typography"], duration: "0-6 мес", salary: "$250–500" },
      { level: "Middle", title: "Middle Designer", skills: ["UX Research", "Prototyping", "Design Systems", "Usability Testing"], duration: "6-18 мес", salary: "$500–1,000" },
      { level: "Senior", title: "Senior Designer", skills: ["Product Strategy", "Advanced UX", "Team Mentoring", "Data-driven Design"], duration: "2-4 года", salary: "$1,000–2,000" },
      { level: "Lead", title: "Design Lead / Head of Design", skills: ["Design Ops", "Cross-team Collaboration", "Vision Setting"], duration: "4+ лет", salary: "$2,000–3,500" },
    ],
  },
  {
    slug: "mobile-developer",
    title: "Mobile Developer",
    description: "Создание приложений для iOS и Android",
    level: "middle",
    skills: ["React Native", "Flutter", "Swift", "Kotlin"],
    whatDoes: [
      "Разрабатывает мобильные приложения (iOS/Android)",
      "Интегрирует с API",
      "Публикует в App Store / Google Play",
      "Добавляет push-уведомления, офлайн-режим и другие функции",
    ],
    companyRole: "В команде инженеров — отвечает за мобильный пользовательский опыт. Часто работает параллельно с фронтендом и бэкендом.",
    roadmap: [
      { level: "Junior", title: "Junior Mobile Dev", skills: ["React Native / Flutter", "UI components", "Navigation"], duration: "0-6 мес", salary: "$300–600" },
      { level: "Middle", title: "Middle Mobile Dev", skills: ["Native APIs", "State Management", "Testing", "CI/CD"], duration: "6-18 мес", salary: "$600–1,300" },
      { level: "Senior", title: "Senior Mobile Dev", skills: ["Performance", "Architecture", "Native modules", "Security"], duration: "2-4 года", salary: "$1,300–2,500" },
      { level: "Lead", title: "Mobile Lead", skills: ["Platform strategy", "Team management", "Cross-platform decisions"], duration: "4+ лет", salary: "$2,500–4,000" },
    ],
  },
  {
    slug: "devops-engineer",
    title: "DevOps Engineer",
    description: "Управление инфраструктурой, CI/CD и процессами деплоя",
    level: "advanced",
    skills: ["Docker", "Linux", "CI/CD", "AWS/GCP"],
    whatDoes: [
      "Настраивает и управляет серверами и инфраструктурой",
      "Создаёт CI/CD пайплайны (автоматический билд/деплой)",
      "Устанавливает системы мониторинга и логирования",
      "Обеспечивает безопасность и аптайм",
    ],
    companyRole: "В команде инженеров — отвечает за стабильную работу всех систем. Строит инфраструктуру для быстрого и безопасного деплоя.",
    roadmap: [
      { level: "Junior", title: "Junior DevOps", skills: ["Linux", "Git", "Docker", "Basic CI/CD"], duration: "0-6 мес", salary: "$400–800" },
      { level: "Middle", title: "Middle DevOps", skills: ["Kubernetes", "Terraform", "Monitoring", "Cloud (AWS/GCP)"], duration: "6-18 мес", salary: "$800–1,800" },
      { level: "Senior", title: "Senior DevOps / SRE", skills: ["Architecture", "Security", "Cost optimization", "Incident management"], duration: "2-4 года", salary: "$1,800–3,500" },
      { level: "Lead", title: "Platform Engineer / Head of Infra", skills: ["Platform strategy", "Team building", "Multi-cloud"], duration: "4+ лет", salary: "$3,500–5,000+" },
    ],
  },
  {
    slug: "product-manager",
    title: "Product Manager",
    description: "Стратегия продукта и управление командой",
    level: "middle",
    skills: ["Agile", "Analytics", "Roadmapping", "Leadership"],
    whatDoes: [
      "Определяет стратегию и дорожную карту продукта",
      "Исследует потребности пользователей",
      "Координирует команды инженеров, дизайна и бизнеса",
      "Отслеживает KPI и метрики",
    ],
    companyRole: "В продуктовой команде — отвечает на вопросы «что» и «зачем». Мини-версия CEO — полностью отвечает за успех продукта.",
    roadmap: [
      { level: "Junior", title: "Associate PM", skills: ["Agile/Scrum", "User Stories", "Basic Analytics", "Communication"], duration: "0-6 мес", salary: "$300–600" },
      { level: "Middle", title: "Product Manager", skills: ["Roadmapping", "A/B Testing", "Stakeholder Management", "Prioritization"], duration: "1-2 года", salary: "$600–1,200" },
      { level: "Senior", title: "Senior PM", skills: ["Product Strategy", "Data Analysis", "Cross-functional Leadership", "Market Analysis"], duration: "2-4 года", salary: "$1,200–2,500" },
      { level: "Lead", title: "Head of Product / CPO", skills: ["Vision Setting", "P&L Ownership", "Portfolio Management", "Org Building"], duration: "5+ лет", salary: "$2,500–4,000+" },
    ],
  },
  {
    slug: "seo-specialist",
    title: "SEO Specialist",
    description: "Продвижение сайта в поисковых системах",
    level: "beginner",
    skills: ["On-page SEO", "Technical SEO", "Content Strategy", "Analytics"],
    whatDoes: [
      "Оптимизирует сайт для Google и других поисковых систем",
      "Исследует ключевые слова и составляет контент-стратегию",
      "Выявляет и устраняет проблемы технического SEO",
      "Анализирует рост органического трафика",
    ],
    companyRole: "В маркетинговой команде — отвечает за органический рост. Работает с контентной, технической и маркетинговой командами.",
    roadmap: [
      { level: "Junior", title: "Junior SEO", skills: ["On-page SEO", "Google Search Console", "Keyword Research"], duration: "0-6 мес", salary: "$200–400" },
      { level: "Middle", title: "SEO Specialist", skills: ["Technical SEO", "Link Building", "Content Strategy", "Analytics"], duration: "6-18 мес", salary: "$400–900" },
      { level: "Senior", title: "Senior SEO / SEO Lead", skills: ["SEO Architecture", "International SEO", "Team Management", "AI SEO"], duration: "2-4 года", salary: "$900–1,800" },
      { level: "Lead", title: "Head of SEO / Growth Lead", skills: ["Growth Strategy", "Cross-channel Marketing", "Budget Management"], duration: "4+ лет", salary: "$1,800–3,000" },
    ],
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    description: "Развитие бизнеса через онлайн-маркетинг и цифровые каналы",
    level: "beginner",
    skills: ["SMM", "Google Ads", "Facebook Ads", "Email Marketing"],
    whatDoes: [
      "Разрабатывает стратегию цифрового маркетинга",
      "Управляет соцсетями и рекламными кампаниями",
      "Оптимизирует маркетинговый бюджет и отслеживает ROI",
      "Определяет целевую аудиторию и составляет контент-план",
    ],
    companyRole: "В маркетинговой команде — отвечает за онлайн-продвижение бренда. Работает с продажами, контентом и продуктовой командой.",
    roadmap: [
      { level: "Junior", title: "Junior Marketer", skills: ["Основы SMM", "Canva", "Email marketing", "Основы аналитики"], duration: "0-6 мес", salary: "$200–450" },
      { level: "Middle", title: "Digital Marketer", skills: ["Google Ads", "Facebook Ads", "A/B Testing", "Marketing Automation"], duration: "6-18 мес", salary: "$450–1,000" },
      { level: "Senior", title: "Senior Marketer", skills: ["Growth Strategy", "Budget Management", "Team Leading", "Data Analysis"], duration: "2-4 года", salary: "$1,000–2,000" },
      { level: "Lead", title: "Head of Marketing / CMO", skills: ["Brand Strategy", "P&L Ownership", "Cross-channel Strategy", "Org Building"], duration: "4+ лет", salary: "$2,000–3,500" },
    ],
  },
  {
    slug: "data-analyst",
    title: "Data Analyst",
    description: "Анализ данных и поддержка бизнес-решений",
    level: "middle",
    skills: ["SQL", "Python", "Excel", "Power BI"],
    whatDoes: [
      "Собирает, очищает и анализирует данные",
      "Создаёт дашборды и отчёты",
      "Даёт рекомендации бизнес-команде на основе данных",
      "Выявляет тренды и строит прогнозные модели",
    ],
    companyRole: "В аналитической команде — помогает принимать решения на основе данных. Работает с продуктовой, маркетинговой и инженерной командами.",
    roadmap: [
      { level: "Junior", title: "Junior Analyst", skills: ["Excel", "Основы SQL", "Google Analytics", "Основы статистики"], duration: "0-6 мес", salary: "$300–600" },
      { level: "Middle", title: "Data Analyst", skills: ["Python/R", "Power BI/Tableau", "A/B Testing", "Statistical Analysis"], duration: "6-18 мес", salary: "$600–1,200" },
      { level: "Senior", title: "Senior Data Analyst", skills: ["Основы Machine Learning", "Data Modeling", "Stakeholder Management", "Mentoring"], duration: "2-4 года", salary: "$1,200–2,500" },
      { level: "Lead", title: "Head of Analytics / Data Lead", skills: ["Data Strategy", "Team Building", "Advanced ML", "Business Intelligence"], duration: "4+ лет", salary: "$2,500–4,000" },
    ],
  },
  {
    slug: "copywriter",
    title: "Copywriter / Content Creator",
    description: "Создание контента, написание текстов и формирование голоса бренда",
    level: "beginner",
    skills: ["Copywriting", "Content Strategy", "SEO Writing", "Storytelling"],
    whatDoes: [
      "Пишет тексты для сайта, рекламы и соцсетей",
      "Составляет контент-стратегию и контент-план",
      "Формирует голос бренда (tone of voice)",
      "Пишет SEO-оптимизированные статьи и блог-посты",
    ],
    companyRole: "В маркетинговой команде — отвечает за голос и сообщения бренда. Работает с дизайнерами, маркетологами и продуктовой командой.",
    roadmap: [
      { level: "Junior", title: "Junior Copywriter", skills: ["Основы копирайтинга", "Грамматика", "Social media writing", "Research"], duration: "0-6 мес", salary: "$150–350" },
      { level: "Middle", title: "Copywriter", skills: ["SEO Writing", "Email Campaigns", "Brand Voice", "Content Calendar"], duration: "6-18 мес", salary: "$350–800" },
      { level: "Senior", title: "Senior Copywriter / Content Lead", skills: ["Content Strategy", "Team Management", "Conversion Copywriting", "AI Tools"], duration: "2-4 года", salary: "$800–1,500" },
      { level: "Lead", title: "Head of Content / Creative Director", skills: ["Editorial Strategy", "Brand Building", "Cross-channel Content", "Budget Management"], duration: "4+ лет", salary: "$1,500–2,500" },
    ],
  },
];

export const levelLabels: Record<string, string> = {
  beginner: "Начальный",
  middle: "Средний",
  advanced: "Продвинутый",
};
